stages:
  - lint
  - test
  - integration
  - build
  - deploy

variables:
  NODE_ENV: test

# ---------------- LINT ----------------
lint:
  image: node:18
  stage: lint
  script:
    - npm ci
    - npx eslint .

# ---------------- UNIT TEST ----------------
unit_test:
  image: node:18
  stage: test
  script:
    - npm ci
    - npx jest

# ---------------- INTEGRATION TEST ----------------
integration_test:
  image: node:18
  stage: integration
  script:
    - echo "Running integration tests"
    - npm ci
    - npx jest --detectOpenHandles

# ---------------- BUILD + PUSH DOCKER IMAGE ----------------
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - echo "Building Docker image with tag $IMAGE_TAG"

    # login to Docker Hub
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

    # build and push image
    - docker build -t $DOCKER_USERNAME/hello-app:$IMAGE_TAG .
    - docker push $DOCKER_USERNAME/hello-app:$IMAGE_TAG

# ---------------- DEPLOY TO KUBERNETES ---------------
deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - kubectl version --client